name: Publish

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: "Use NodeJS 20"
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - name: "Setup npm"
        run: |
          npm set @gsmsdev12:registry=https://npm.pkg.github.com/
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.G_TOKEN }}"

      - name: Install Packages
        run: npm install

      - name: "Commit lockfile if changed"
        # Only commit changes to package-lock.json if it was actually modified
        run: |
          if [ -n "$(git status package-lock.json --porcelain)" ]; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: update package-lock.json [skip ci]"
          fi
      - name: "Version"
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          
          if [ ${{ github.base_ref }} = development ]; then
            npm lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            lerna version --conventional-commits --conventional-prerelease --yes
          fi
      - name: "Publish"
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          # Publish from the newly created tags
          lerna publish from-git --yes