name: Publish

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: "Use NodeJS 20"
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - name: "Setup npm"
        run: |
          npm set @gsmsdev:registry=https://npm.pkg.github.com/gsmsdev
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.G_TOKEN }}"
      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          
          git stash
          git checkout ${{ github.ref }}
          
          if [ ${{ github.base_ref }} = development ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes
          fi
          
          npx lerna publish from-git --yes